const root=document.querySelector('#app');
const esc=v=>String(v??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;');
const num=v=>new Intl.NumberFormat('ru-RU',{maximumFractionDigits:2}).format(Number(v)||0);
let state={loading:true,error:null,data:null,view:'platform'};
const nav=[['platform','Платформа'],['companies','Компании'],['market','Market'],['categories','Категории'],['ai','ИИ'],['autonomy','Автономность'],['integrations','Интеграции'],['moderation','Модерация'],['experiments','Эксперименты'],['flags','Feature Flags'],['audit','Audit'],['health','Health']];
async function load(){state.loading=true;render();try{const res=await fetch('/api/v1/control-plane',{credentials:'include'});const json=await res.json();if(!res.ok)throw new Error(res.status===401||res.status===403?'Нужен вход администратора платформы':json.error||'Не удалось загрузить Control Plane');state.data=json;state.error=null}catch(e){state.error=e.message}finally{state.loading=false;render()}}
function shell(content){return `<div class="cp-shell"><aside class="cp-nav"><div class="brand"><div class="brand-mark">E</div><div class="brand-copy"><strong>EINEIRO</strong><span>Control Plane</span></div></div>${nav.map(([id,label])=>`<button class="nav-button ${state.view===id?'active':''}" data-cp="${id}">${label}</button>`).join('')}</aside><main class="cp-main"><header class="adm-head"><div><b>EINEIRO</b><span>CONTROL PLANE</span></div><div class="adm-live">● PLATFORM</div></header>${content}</main></div>`}
function render(){if(state.loading){root.innerHTML=shell('<section class="adm-hero"><div><span>CONTROL PLANE</span><h1>Собираю состояние платформы…</h1></div></section>');return}if(state.error){root.innerHTML=shell(`<section class="adm-hero"><div><span>ДОСТУП</span><h1>${esc(state.error)}</h1><button data-a="reload">Повторить</button></div></section>`);return}root.innerHTML=shell(view())}
function view(){return ({platform,companies,market,categories,ai,autonomy,integrations,moderation,experiments,flags,audit,health}[state.view]||platform)()}
function platform(){const d=state.data,h=d.health||{};return `<section class="adm-hero"><div><span>УПРАВЛЕНИЕ ПО ИСКЛЮЧЕНИЯМ</span><h1>Платформа как единая система.</h1><p>Компании, Market, ИИ, эксперименты, модерация и rollout управляются из одного слоя.</p></div><div class="adm-ring"><strong>${d.autonomy.score}%</strong><span>автономность</span></div></section><section class="adm-grid"><article class="adm-card"><span>Компании</span><strong>${d.companies.length}</strong></article><article class="adm-card"><span>Products / Offers</span><strong>${d.market.products} / ${d.market.offers}</strong></article><article class="adm-card"><span>Решения ИИ</span><strong>${d.ai.decisions}</strong><small>${d.ai.requiresApproval} требуют человека</small></article><article class="adm-card"><span>Health</span><strong>${esc(h.status||'unknown')}</strong><small>${Number(h.totals?.dlq||0)} DLQ · ${Number(h.totals?.connectorErrors||0)} ошибок каналов</small></article></section>`}
function companies(){return panel('КОМПАНИИ','Состояние арендаторов',state.data.companies.map(x=>row(x.companyId,`${x.users} пользователей · ${x.products} товаров · ${x.offers} предложений · ${x.orders} заказов`,`${x.decisions} решений`)).join(''))}
function market(){const m=state.data.market;return `<section class="adm-grid"><article class="adm-card"><span>Products</span><strong>${m.products}</strong></article><article class="adm-card"><span>Offers</span><strong>${m.offers}</strong></article><article class="adm-card"><span>Orders</span><strong>${m.orders}</strong></article><article class="adm-card"><span>Незакрытый спрос</span><strong>${m.unservedDemand}</strong></article></section>`}
function categories(){return panel('КАТЕГОРИИ','Распределение товара',state.data.categories.map(x=>row(x.id,`${x.count} товаров`,'')).join('')||'<div class="adm-empty">Категорий пока нет</div>')}
function ai(){const a=state.data.ai;return `<section class="adm-grid"><article class="adm-card"><span>Решения</span><strong>${a.decisions}</strong></article><article class="adm-card"><span>Исполнено</span><strong>${a.executed}</strong></article><article class="adm-card"><span>Нужен человек</span><strong>${a.requiresApproval}</strong></article><article class="adm-card"><span>Расход</span><strong>${num(a.costUnits)} у.е.</strong></article></section>`}
function autonomy(){const a=state.data.autonomy;return `<section class="adm-hero"><div><span>AUTONOMY ENGINE</span><h1>${a.score}% решений без человека.</h1><p>Считаются только действия и решения, которые иначе потребовали бы участия человека.</p></div><div class="adm-ring"><strong>${a.score}%</strong><span>коэффициент</span></div></section><section class="adm-grid"><article class="adm-card"><span>Автодействия</span><strong>${a.executedActions}</strong></article><article class="adm-card"><span>Решения человека</span><strong>${a.humanDecisions}</strong></article></section>`}
function integrations(){const i=state.data.integrations;return `<section class="adm-grid"><article class="adm-card"><span>Активные подключения</span><strong>${i.connections}</strong></article><article class="adm-card"><span>Ошибки</span><strong>${i.errors}</strong></article></section>`}
function moderation(){const m=state.data.moderation||{};const exceptions=m.recentExceptions||[],appeals=m.recentAppeals||[];return `<section class="adm-grid"><article class="adm-card"><span>Всего дел</span><strong>${Number(m.total||0)}</strong></article><article class="adm-card"><span>Ожидают AI</span><strong>${Number(m.aiWaiting||0)}</strong></article><article class="adm-card"><span>Нужен человек</span><strong>${Number(m.humanExceptions||0)}</strong></article><article class="adm-card"><span>Апелляции</span><strong>${Number(m.appealsOpen||0)}</strong></article><article class="adm-card"><span>Карантин</span><strong>${Number(m.quarantined||0)}</strong></article><article class="adm-card"><span>Инциденты</span><strong>${Number(m.incidentsOpen||0)}</strong></article></section>${panel('РЕДКИЕ ИСКЛЮЧЕНИЯ','Только конфликт AI, новая улика, правовой вопрос или критический вред',exceptions.map(x=>row(x.companyId,(x.reasonCodes||[]).join(', ')||x.moderationCaseId,x.priority||'P1')).join('')||'<div class="adm-empty">Открытых исключений нет</div>')}${panel('АПЕЛЛЯЦИИ','Новые доказательства без обхода жёстких правил',appeals.map(x=>row(x.companyId,`${x.previousDecision||'решение'} · ${x.moderationCaseId}`,x.status||'open')).join('')||'<div class="adm-empty">Открытых апелляций нет</div>')}<section class="adm-panel"><div class="adm-backup">Алгоритмы принимают обычные решения. AI вызывается только при смысловой неоднозначности. Человек получает исключительно редкие исключения P0/P1.</div></section>`}
function experiments(){const e=state.data.experiments;return `<section class="adm-grid"><article class="adm-card"><span>Эксперименты</span><strong>${e.tests}</strong></article><article class="adm-card"><span>Идут сейчас</span><strong>${e.running}</strong></article></section><section class="adm-panel"><div class="adm-backup">Marketing Memory хранит результат, контрольную группу и вывод каждого эксперимента.</div></section>`}
function flags(){const f=state.data.featureFlags;return `<section class="adm-grid"><article class="adm-card"><span>Всего флагов</span><strong>${f.total}</strong></article><article class="adm-card"><span>Включено</span><strong>${f.enabled}</strong></article></section><section class="adm-panel"><div class="adm-backup">Rollout: internal → pilot → % пользователей → категория/регион → all. Любой флаг можно откатить.</div></section>`}
function audit(){return `<section class="adm-grid"><article class="adm-card"><span>Audit events</span><strong>${state.data.audit.events}</strong></article></section><section class="adm-panel"><div class="adm-backup">Журнал хранит actor, action, object, reason, decision, policy, before, after, result и rollback.</div></section>`}
function health(){const h=state.data.health||{status:'unknown',totals:{},companies:[]};const t=h.totals||{};return `<section class="adm-hero"><div><span>TECHNICAL HEALTH</span><h1>${healthTitle(h.status)}</h1><p>Сводка сервисов, очередей, интеграций, ИИ, решений и восстановления.</p></div><div class="adm-ring"><strong>${esc(String(h.status||'unknown').toUpperCase())}</strong><span>platform</span></div></section><section class="adm-grid"><article class="adm-card"><span>DLQ</span><strong>${Number(t.dlq||0)}</strong></article><article class="adm-card"><span>Повторы</span><strong>${Number(t.retries||0)}</strong></article><article class="adm-card"><span>Ошибки каналов</span><strong>${Number(t.connectorErrors||0)}</strong></article><article class="adm-card"><span>Ошибки webhook</span><strong>${Number(t.webhookFailures||0)}</strong></article><article class="adm-card"><span>Ошибки ИИ</span><strong>${Number(t.aiErrors||0)}</strong></article><article class="adm-card"><span>Failed decisions</span><strong>${Number(t.decisionFailures||0)}</strong></article><article class="adm-card"><span>Policy denials</span><strong>${Number(t.policyDenials||0)}</strong></article><article class="adm-card"><span>DR ready</span><strong>${Number(t.drReady||0)} / ${h.companies?.length||0}</strong></article></section>${panel('КОМПАНИИ','Health по арендаторам',(h.companies||[]).map(x=>{const o=x.observability||{},d=x.disasterRecovery||{};return row(x.companyId,`DLQ ${o.dlqSize||0} · connectors ${o.connectorHealth?.error||0} · AI errors ${o.aiProvider?.errors||0} · DR ${d.status||'unknown'}`,x.status||'unknown')}).join('')||'<div class="adm-empty">Нет данных health</div>')}`}
function healthTitle(status){if(status==='ok')return'Платформа работает штатно.';if(status==='degraded')return'Есть деградации, но платформа работает.';if(status==='critical')return'Есть критические технические отклонения.';return'Состояние ещё не подтверждено.'}
function panel(k,t,body){return `<section class="adm-panel"><div class="adm-title"><div><span>${k}</span><h2>${t}</h2></div></div>${body}</section>`}
function row(title,sub,right){return `<div class="adm-row"><i class="good"></i><div><b>${esc(title)}</b><span>${esc(sub)}</span></div><strong>${esc(right)}</strong></div>`}
root.addEventListener('click',e=>{const n=e.target.closest('[data-cp]');if(n){state.view=n.dataset.cp;render();return}if(e.target.closest('[data-a="reload"]'))load()});
load();
