import {plans,grace,roles,connectors,platformLayers,invariants} from './platform-core.js';
const KEY='eineiro-addons-v1';
const seed={plan:'Autopilot',graceActive:false,role:'owner',conversations:[
 {id:'C-41',channel:'Avito',customer:'Илья',product:'Фара Focus III',unread:2,last:'Есть доставка?',sla:3,status:'open'},
 {id:'C-40',channel:'EINEIRO Market',customer:'Максим',product:'АКПП A6GF1',unread:0,last:'Оплачу сегодня',sla:1,status:'qualified'},
 {id:'C-39',channel:'VK',customer:'Роман',product:'Бампер Polo',unread:1,last:'Сделаете скидку?',sla:11,status:'attention'}
],orders:[
 {id:'O-1008',buyer:'Максим',items:'АКПП A6GF1',amount:98000,status:'packing',shipment:'ожидает ТК'},
 {id:'O-1007',buyer:'Алексей',items:'Двигатель G4FC',amount:185000,status:'shipped',shipment:'CDEK 1468821'}
],audit:[
 {time:'10:42',actor:'AI-РОП',action:'Перераспределил лид L-1042',result:'SLA соблюдён'},
 {time:'10:18',actor:'AI Seller',action:'Отправил follow-up C-40',result:'Клиент вернулся'},
 {time:'09:57',actor:'Price Lab',action:'Заблокировал цену ниже минимума',result:'Маржа сохранена'}
]};
function load(){try{return JSON.parse(localStorage.getItem(KEY))||structuredClone(seed)}catch{return structuredClone(seed)}}
let state=load();const save=()=>localStorage.setItem(KEY,JSON.stringify(state));
const esc=v=>String(v??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;');
const money=v=>new Intl.NumberFormat('ru-RU').format(v)+' ₽';
function ensureNav(){const nav=document.querySelector('.nav');if(!nav||nav.querySelector('[data-ea="inbox"]'))return;const items=[['inbox','Сообщения','✦'],['marketplace','Заказы Market','◫'],['settings','Платформа','⚙']];for(const [id,label,ic] of items){const b=document.createElement('button');b.className='nav-button';b.dataset.ea=id;b.innerHTML=`<span style="width:19px;text-align:center">${ic}</span><span>${label}</span>`;nav.append(b)} }
function setTitle(title,sub){const h=document.querySelector('.top-title h1'),p=document.querySelector('.top-title p');if(h)h.textContent=title;if(p)p.textContent=sub}
function root(){return document.querySelector('#view-root')}
function inbox(){setTitle('Сообщения','Unified Inbox · все каналы в одном месте');root().innerHTML=`<section class="view"><div class="core-grid cols-4"><article class="core-card"><div class="eyebrow">Непрочитано</div><div class="core-kpi">${state.conversations.reduce((s,c)=>s+c.unread,0)}</div></article><article class="core-card"><div class="eyebrow">SLA нарушен</div><div class="core-kpi">${state.conversations.filter(c=>c.sla>5).length}</div></article><article class="core-card"><div class="eyebrow">Каналы</div><div class="core-kpi">${new Set(state.conversations.map(c=>c.channel)).size}</div></article><article class="core-card"><div class="eyebrow">AI Seller</div><div class="core-kpi">ON</div><div class="core-sub">ответы только по фактам системы</div></article></div><article class="core-card" style="margin-top:14px"><div class="core-topline"><div><span class="core-badge ai">UNIFIED INBOX</span><h3>Чат → клиент → товар → продавец → заказ</h3></div></div>${state.conversations.map(c=>`<div class="lead-row"><div><div class="row-title">${esc(c.customer)} · ${esc(c.channel)}</div><div class="row-meta">${esc(c.product)} · ${esc(c.last)}</div></div><div><span class="sla ${c.sla<=5?'good':c.sla<=10?'warn':'bad'}">${c.sla} мин</span><div class="row-meta">SLA</div></div><div><span class="core-badge ${c.status==='attention'?'bad':'good'}">${esc(c.status)}</span></div><button class="core-btn ai" data-addon="reply" data-id="${c.id}">Предложить ответ</button></div>`).join('')}</article></section>`}
function marketplace(){setTitle('Заказы EINEIRO Market','Транзакции, упаковка, отправка и tracking');root().innerHTML=`<section class="view"><article class="core-card"><div class="core-topline"><div><span class="core-badge good">0% комиссия за продажу</span><h3>Order flow</h3><p>Продавец формирует заказ → склад получает задачу → упаковка → отправка → tracking.</p></div></div>${state.orders.map(o=>`<div class="task-row"><span class="core-badge ${o.status==='shipped'?'good':'warn'}">${o.status}</span><div><div class="row-title">${o.id} · ${esc(o.buyer)}</div><div class="row-meta">${esc(o.items)} · ${money(o.amount)}</div></div><span class="row-meta">${esc(o.shipment)}</span><button class="core-btn" data-addon="order" data-id="${o.id}">${o.status==='packing'?'Отправлено':'Tracking'}</button></div>`).join('')}</article></section>`}
function settings(){setTitle('Платформа','Тариф, роли, policies, audit и системные слои');const p=plans[state.plan];root().innerHTML=`<section class="view"><div class="core-grid cols-3"><article class="core-card"><div class="eyebrow">Тариф</div><div class="core-kpi">${state.plan}</div><div class="core-sub">${p.price===0?'бесплатно':p.price+' / мес'}</div></article><article class="core-card"><div class="eyebrow">Роль</div><div class="core-kpi">${state.role}</div><div class="core-sub">permissions применяются по policy</div></article><article class="core-card"><div class="eyebrow">Grace</div><div class="core-kpi">${state.graceActive?'7 дней':'нет'}</div><div class="core-sub">AI нет · склад ручной · barcode camera да</div></article></div><div class="core-grid cols-2" style="margin-top:14px"><article class="core-card"><div class="eyebrow">CAPABILITY MATRIX</div><table class="mini-table"><tbody><tr><td>AI</td><td>${p.ai?'да':'нет'}</td></tr><tr><td>Склад</td><td>${p.warehouse}</td></tr><tr><td>Barcode camera</td><td>${p.barcodeCamera?'да':'нет'}</td></tr><tr><td>API / feeds</td><td>${p.publishing?'да':'нет'}</td></tr><tr><td>Automation</td><td>${String(p.automation)}</td></tr></tbody></table><div class="tabs-row" style="margin-top:12px">${Object.keys(plans).map(x=>`<button class="core-btn ${x===state.plan?'primary':''}" data-addon="plan" data-plan="${x}">${x}</button>`).join('')}</div></article><article class="core-card"><div class="eyebrow">РОЛИ</div>${Object.entries(roles).map(([r,g])=>`<div class="integration-row"><div class="row-title">${r}</div><div class="row-meta">${g.join(', ')}</div><span class="core-badge">policy</span></div>`).join('')}</article></div><div class="core-grid cols-2" style="margin-top:14px"><article class="core-card"><div class="eyebrow">AUDIT LOG</div>${state.audit.map(a=>`<div class="ai-event"><span class="core-badge ai">${a.actor}</span><div><div class="row-title">${esc(a.action)}</div><div class="row-meta">${esc(a.result)}</div></div><time>${a.time}</time></div>`).join('')}</article><article class="core-card"><div class="eyebrow">LEVEL‑4 PLATFORM LAYERS</div>${platformLayers.map(x=>`<div class="integration-row"><div class="row-title">${esc(x)}</div><span></span><span class="core-badge good">restored</span></div>`).join('')}</article></div><article class="core-card" style="margin-top:14px"><div class="eyebrow">КАНАЛЫ / CONNECTOR FRAMEWORK</div><p>Publishing: ${connectors.publishing.join(' · ')}<br>Messaging: ${connectors.messaging.join(' · ')}<br>Pilot: ${connectors.pilot.join(' · ')}</p><div class="alert-note" style="margin-top:12px">Инварианты: 0% комиссия за продажу; управление по исключениям; Market без каталога до запроса; camera safe zone неприкосновенна; ≤3 контекстных offer; Clean View сохраняет размещённый товар.</div></article></section>`}
function renderAddon(id){document.querySelectorAll('.nav-button').forEach(x=>x.classList.toggle('active',x.dataset.ea===id));if(id==='inbox')inbox();if(id==='marketplace')marketplace();if(id==='settings')settings()}
document.addEventListener('click',e=>{const nav=e.target.closest('[data-ea]');if(nav){e.preventDefault();renderAddon(nav.dataset.ea);return}const b=e.target.closest('[data-addon]');if(!b)return;if(b.dataset.addon==='plan'){state.plan=b.dataset.plan;save();settings()}if(b.dataset.addon==='reply'){const c=state.conversations.find(x=>x.id===b.dataset.id);if(c){c.unread=0;c.last='AI: Готов ответ с учётом наличия, гарантии и доставки';state.audit.unshift({time:new Date().toLocaleTimeString('ru-RU',{hour:'2-digit',minute:'2-digit'}),actor:'AI Seller',action:`Предложен ответ ${c.id}`,result:'ожидает подтверждения'});save();inbox()}}if(b.dataset.addon==='order'){const o=state.orders.find(x=>x.id===b.dataset.id);if(o&&o.status==='packing'){o.status='shipped';o.shipment='tracking создан автоматически';save();marketplace()}}});
const observer=new MutationObserver(()=>ensureNav());observer.observe(document.documentElement,{subtree:true,childList:true});ensureNav();
