import {plans,grace,roles,connectors,platformLayers,invariants} from './platform-core.js';
const KEY='eineiro-addons-v2';
const state={plan:'Autopilot',graceActive:false,role:'owner',audit:[]};
try{Object.assign(state,JSON.parse(localStorage.getItem(KEY)||'{}'))}catch{}
const save=()=>localStorage.setItem(KEY,JSON.stringify(state));
const esc=v=>String(v??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;');
const money=v=>new Intl.NumberFormat('ru-RU').format(Number(v)||0)+' ₽';

function ensureNav(){const nav=document.querySelector('.nav');if(!nav||nav.querySelector('[data-ea="inbox"]'))return;for(const [id,label,ic] of [['inbox','Сообщения','✦'],['marketplace','Заказы Market','◫'],['settings','Платформа','⚙']]){const b=document.createElement('button');b.className='nav-button';b.dataset.ea=id;b.innerHTML=`<span style="width:19px;text-align:center">${ic}</span><span>${label}</span>`;nav.append(b)}}
function setTitle(title,sub){const h=document.querySelector('.top-title h1'),p=document.querySelector('.top-title p');if(h)h.textContent=title;if(p)p.textContent=sub}
function root(){return document.querySelector('#view-root')}
function loading(title){root().innerHTML=`<section class="view"><article class="core-card"><div class="eyebrow">${esc(title)}</div><div class="core-sub">Получаю реальные данные системы…</div></article></section>`}
function errorView(title,message){root().innerHTML=`<section class="view"><article class="core-card"><div class="eyebrow">${esc(title)}</div><h3>${esc(message)}</h3><div class="core-sub">Демонстрационные данные не подставляются.</div></article></section>`}

async function inbox(){setTitle('Сообщения','Все подключённые каналы в одном месте');loading('ЕДИНЫЙ ЦЕНТР СООБЩЕНИЙ');try{const res=await fetch('/api/v1/inbox/conversations',{credentials:'include'});const j=await res.json();if(!res.ok)throw new Error(j.error||'Сообщения недоступны');const items=j.items||[];root().innerHTML=`<section class="view"><div class="core-grid cols-3"><article class="core-card"><div class="eyebrow">Диалоги</div><div class="core-kpi">${items.length}</div></article><article class="core-card"><div class="eyebrow">Непрочитано</div><div class="core-kpi">${items.reduce((s,c)=>s+Number(c.unread||0),0)}</div></article><article class="core-card"><div class="eyebrow">Каналы</div><div class="core-kpi">${new Set(items.map(c=>c.channel)).size}</div></article></div><article class="core-card" style="margin-top:14px"><div class="eyebrow">ДИАЛОГИ</div>${items.map(c=>{const last=c.messages?.[c.messages.length-1];return `<div class="lead-row"><div><div class="row-title">${esc(c.channel)} · ${esc(c.conversationExternalId)}</div><div class="row-meta">${esc(last?.text||'Без текста')}</div></div><div><span class="core-badge ${c.unread?'warn':'good'}">${c.unread||0} новых</span></div><button class="core-btn ai" data-addon="open-conversation" data-channel="${esc(c.channel)}" data-conversation="${esc(c.conversationExternalId)}">Открыть</button></div>`}).join('')||'<div class="core-sub">Диалогов пока нет.</div>'}</article></section>`}catch(e){errorView('ЕДИНЫЙ ЦЕНТР СООБЩЕНИЙ',e.message)}}

async function marketplace(){setTitle('Заказы EINEIRO Market','Заказ → сборка → отправка → получение');loading('ЗАКАЗЫ MARKET');try{const res=await fetch('/api/v1/business/snapshot',{credentials:'include'});const j=await res.json();if(!res.ok)throw new Error(j.error||'Заказы недоступны');const orders=j.orders||[];root().innerHTML=`<section class="view"><article class="core-card"><div class="core-topline"><div><span class="core-badge good">0% комиссии за продажу</span><h3>Заказы</h3><p>Внешние расходы — эквайринг, доставка, возвраты — показываются отдельно.</p></div></div>${orders.map(o=>`<div class="task-row"><span class="core-badge ${o.status==='shipped'||o.status==='delivered'?'good':'warn'}">${esc(o.status||'создан')}</span><div><div class="row-title">${esc(o.id)}</div><div class="row-meta">${(o.items||[]).map(x=>esc(x.name||x.productId||'товар')).join(', ')||'товары'}</div></div><strong>${money(o.total||o.amount||0)}</strong></div>`).join('')||'<div class="core-sub">Заказов пока нет.</div>'}</article></section>`}catch(e){errorView('ЗАКАЗЫ MARKET',e.message)}}

function settings(){setTitle('Платформа','Тариф, роли, правила и системные слои');const p=plans[state.plan]||plans.Start;root().innerHTML=`<section class="view"><div class="core-grid cols-3"><article class="core-card"><div class="eyebrow">Тариф</div><div class="core-kpi">${state.plan}</div><div class="core-sub">${p.price===0?'бесплатно':p.price+' / мес'}</div></article><article class="core-card"><div class="eyebrow">Роль</div><div class="core-kpi">${state.role}</div><div class="core-sub">права применяются сервером</div></article><article class="core-card"><div class="eyebrow">Льготный период</div><div class="core-kpi">${state.graceActive?'7 дней':'нет'}</div><div class="core-sub">ИИ нет · склад вручную · сканирование камерой да</div></article></div><div class="core-grid cols-2" style="margin-top:14px"><article class="core-card"><div class="eyebrow">ВОЗМОЖНОСТИ</div><table class="mini-table"><tbody><tr><td>ИИ</td><td>${p.ai?'да':'нет'}</td></tr><tr><td>Склад</td><td>${p.warehouse==='full'?'полный':'ручной'}</td></tr><tr><td>Сканирование камерой</td><td>${p.barcodeCamera?'да':'нет'}</td></tr><tr><td>Публикации</td><td>${p.publishing?'да':'нет'}</td></tr><tr><td>Автоматизация</td><td>${p.automation==='recommend'?'рекомендации':p.automation==='execute-with-policy'?'исполнение по правилам':'нет'}</td></tr></tbody></table><div class="tabs-row" style="margin-top:12px">${Object.keys(plans).map(x=>`<button class="core-btn ${x===state.plan?'primary':''}" data-addon="plan" data-plan="${x}">${x}</button>`).join('')}</div></article><article class="core-card"><div class="eyebrow">РОЛИ</div>${Object.entries(roles).map(([r,g])=>`<div class="integration-row"><div class="row-title">${esc(r)}</div><div class="row-meta">${g.length===1&&g[0]==='*'?'полный доступ':g.length+' разрешений'}</div><span class="core-badge">правила</span></div>`).join('')}</article></div><article class="core-card" style="margin-top:14px"><div class="eyebrow">КАНОНИЧЕСКИЕ ПРАВИЛА</div><div class="alert-note">0% комиссии за продажу · управление по исключениям · камера как основной интерфейс Market · безопасная зона камеры неприкосновенна · количество объектов определяется запросом · у каждого объекта свой полный каталог вариантов · чистый вид сохраняет все размещённые товары.</div></article><article class="core-card" style="margin-top:14px"><div class="eyebrow">СИСТЕМНЫЕ СЛОИ</div>${platformLayers.map(x=>`<div class="integration-row"><div class="row-title">${esc(x)}</div><span class="core-badge good">восстановлено</span></div>`).join('')}</article></section>`}

function renderAddon(id){document.querySelectorAll('.nav-button').forEach(x=>x.classList.toggle('active',x.dataset.ea===id));if(id==='inbox')inbox();if(id==='marketplace')marketplace();if(id==='settings')settings()}
document.addEventListener('click',e=>{const nav=e.target.closest('[data-ea]');if(nav){e.preventDefault();renderAddon(nav.dataset.ea);return}const b=e.target.closest('[data-addon]');if(!b)return;if(b.dataset.addon==='plan'){state.plan=b.dataset.plan;save();settings()}if(b.dataset.addon==='open-conversation'){openConversation(b.dataset.channel,b.dataset.conversation)}});
async function openConversation(channel,conversationExternalId){loading('ДИАЛОГ');try{const res=await fetch('/api/v1/inbox/conversations',{credentials:'include'});const j=await res.json();if(!res.ok)throw new Error(j.error||'Диалог недоступен');const c=(j.items||[]).find(x=>x.channel===channel&&x.conversationExternalId===conversationExternalId);if(!c)throw new Error('Диалог не найден');root().innerHTML=`<section class="view"><article class="core-card"><div class="core-topline"><div><div class="eyebrow">${esc(channel)}</div><h3>${esc(conversationExternalId)}</h3></div><button class="core-btn" data-ea="inbox">Назад</button></div>${(c.messages||[]).map(m=>`<div class="ai-event"><span class="core-badge ${m.direction==='outbound'?'ai':'good'}">${m.direction==='outbound'?'мы':'клиент'}</span><div><div class="row-title">${esc(m.text||'')}</div><div class="row-meta">${esc(m.sentAt||m.receivedAt||m.createdAt||'')}</div></div></div>`).join('')}<form id="inbox-reply" style="margin-top:14px;display:flex;gap:8px"><input name="text" required placeholder="Ответ" style="flex:1"><button class="core-btn ai">Отправить</button></form></article></section>`;document.querySelector('#inbox-reply')?.addEventListener('submit',async e=>{e.preventDefault();const text=new FormData(e.currentTarget).get('text');const r=await fetch('/api/v1/inbox/send',{method:'POST',credentials:'include',headers:{'Content-Type':'application/json','X-CSRF-Token':getCookie('eineiro_csrf')},body:JSON.stringify({channel,conversationExternalId,text,clientRequestId:crypto.randomUUID()})});const out=await r.json();if(!r.ok)throw new Error(out.error||'Не удалось отправить');openConversation(channel,conversationExternalId)})}catch(e){errorView('ДИАЛОГ',e.message)}}
function getCookie(name){return document.cookie.split(';').map(x=>x.trim()).find(x=>x.startsWith(name+'='))?.slice(name.length+1)||''}
const observer=new MutationObserver(()=>ensureNav());observer.observe(document.documentElement,{subtree:true,childList:true});ensureNav();
