const KEY='eineiro-dashboard-layout-v1';
const defaults={order:['director','exceptions','sla','ai','tasks','activity'],hidden:[]};
function load(){try{return {...defaults,...JSON.parse(localStorage.getItem(KEY)||'{}')}}catch{return structuredClone(defaults)}}
let state=load();const save=()=>localStorage.setItem(KEY,JSON.stringify(state));

function dashboard(){return document.querySelector('#view-root .view')}
function cards(){const root=dashboard();if(!root)return[];const list=[...root.querySelectorAll('.core-card')];return list.map((el,i)=>({el,key:i===0?'director':['exceptions','sla','ai','tasks'][i-1]||`activity-${i}`}))}
function apply(){const root=dashboard();if(!root)return;const all=cards();for(const c of all){c.el.dataset.dashboardCard=c.key;c.el.style.display=state.hidden.includes(c.key)?'none':''}const parentMap=new Map();for(const c of all)parentMap.set(c.key,c.el.parentElement);for(const key of state.order){const c=all.find(x=>x.key===key);if(c&&c.el.parentElement) c.el.parentElement.append(c.el)}ensureButton()}
function ensureButton(){const top=document.querySelector('.top-actions');if(!top||top.querySelector('[data-layout="open"]'))return;const b=document.createElement('button');b.className='core-btn';b.dataset.layout='open';b.textContent='Настроить экран';top.prepend(b)}
function panel(){document.querySelector('#layout-panel')?.remove();const all=cards();const p=document.createElement('div');p.id='layout-panel';p.className='layout-panel';p.innerHTML=`<div class="layout-panel-head"><b>Главный экран</b><button data-layout="close">×</button></div><p>Скрывай лишнее и меняй порядок блоков. Настройка сохраняется отдельно для этого браузера.</p>${all.map((c,i)=>`<div class="layout-row"><label><input type="checkbox" data-layout="visible" data-key="${c.key}" ${state.hidden.includes(c.key)?'':'checked'}> ${c.key}</label><div><button data-layout="up" data-key="${c.key}">↑</button><button data-layout="down" data-key="${c.key}">↓</button></div></div>`).join('')}<button class="core-btn" data-layout="reset">Сбросить</button>`;document.body.append(p)}
function move(key,delta){const order=[...state.order];if(!order.includes(key))order.push(key);const i=order.indexOf(key),j=Math.max(0,Math.min(order.length-1,i+delta));[order[i],order[j]]=[order[j],order[i]];state.order=order;save();apply();panel()}
document.addEventListener('click',e=>{const b=e.target.closest('[data-layout]');if(!b)return;const a=b.dataset.layout;if(a==='open')panel();if(a==='close')document.querySelector('#layout-panel')?.remove();if(a==='up')move(b.dataset.key,-1);if(a==='down')move(b.dataset.key,1);if(a==='reset'){state=structuredClone(defaults);save();apply();panel()}});
document.addEventListener('change',e=>{const x=e.target.closest('[data-layout="visible"]');if(!x)return;state.hidden=x.checked?state.hidden.filter(k=>k!==x.dataset.key):[...new Set([...state.hidden,x.dataset.key])];save();apply()});
const obs=new MutationObserver(()=>apply());obs.observe(document.documentElement,{subtree:true,childList:true});apply();
