const root=document.querySelector('#app');
const $=(s,r=document)=>r.querySelector(s);
const esc=v=>String(v??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;');
const money=v=>new Intl.NumberFormat('ru-RU').format(Number(v)||0)+' ₽';
const fallbackInventory={
  shelf:Array.from({length:18},(_,i)=>({id:`S-${i+1}`,name:`Полка ${i+1}`,price:6900+i*310,relevance:.99-i*.01})),
  vase:Array.from({length:36},(_,i)=>({id:`V-${i+1}`,name:`Ваза ${i+1}`,price:1900+i*120,relevance:.99-i*.006})),
  book:Array.from({length:54},(_,i)=>({id:`B-${i+1}`,name:`Книга ${i+1}`,price:900+i*65,relevance:.99-i*.004}))
};
let state={camera:false,clean:false,query:'',stream:null,listening:false,catalogOpen:false,activeSlot:null,slots:[],processing:false,clarification:null,backend:'idle'};
function slot(id){return state.slots.find(s=>s.id===id)}
function sceneObjects(){return state.slots.map((s,i)=>s.selected?`<button class="scene-slot" style="--x:${s.anchor?.x??(35+i*18)}%;--y:${s.anchor?.y??45}%" data-a="slot" data-slot="${s.id}"><span class="scene-slot-label">${esc(s.label)}</span><b>${esc(s.selected.name)}</b><small>${s.catalog.total??s.catalog.items.length} вариантов</small></button>`:'').join('')}
function slotTabs(){return state.slots.map(s=>`<button class="slot-tab ${state.activeSlot===s.id?'active':''}" data-a="slot" data-slot="${s.id}"><b>${esc(s.label)}</b><span>${esc(s.selected?.name||'не выбран')}</span></button>`).join('')}
function productCard(p,i,slotId){const s=slot(slotId);return `<button class="product-card ${s?.selected?.id===p.id?'selected':''}" data-a="replace" data-slot="${slotId}" data-id="${p.id}"><span class="product-rank">${String(i+1).padStart(2,'0')}</span><b>${esc(p.name)}</b><small>${Math.round(Number(p.relevance||0)*100)}% · ${money(p.price)}</small></button>`}
function draw(){const active=slot(state.activeSlot),list=active?.catalog?.items||[];root.innerHTML=`<main class="mkt"><header class="mkt-head"><div class="mkt-brand">EINEIRO <span>market</span></div><div class="mkt-status">${state.processing?'ANALYZING':state.camera?'LIVE CAMERA':state.backend==='api'?'AI READY':'READY'}</div></header><section class="mkt-stage ${state.clean?'clean':''}"><div class="mkt-scene"><video id="camera" autoplay playsinline muted></video><div class="scene-fallback"></div><div class="scan-lines"></div><div class="safe-zone"></div>${sceneObjects()}<div class="intent"><b>${state.processing?'Понимаю сцену…':state.clarification?esc(state.clarification):state.query?esc(state.query):'Покажи, что хочешь'}</b><span>${state.processing?'Несколько кадров + голос → intent → товары':state.slots.length?`${state.slots.length} объектов · у каждого свой каталог`:'Камера и голос — основной интерфейс запроса'}</span></div></div><div class="mkt-controls"><button data-a="fav">♡</button><button class="camera-main ${state.camera?'on':''}" data-a="camera">◎</button><button data-a="voice">${state.listening?'●':'◉'}</button></div>${state.camera&&state.slots.length?`<div class="slot-dock">${slotTabs()}<button class="catalog-toggle" data-a="catalog">Варианты</button></div>`:''}${state.catalogOpen&&active?`<aside class="catalog-drawer"><div class="catalog-head"><div><b>${esc(active.label)} — варианты</b><span>${active.catalog.total} релевантных товаров · меняется только этот объект</span></div><button data-a="catalog">×</button></div><div class="catalog-grid">${list.map((p,i)=>productCard(p,i,active.id)).join('')}</div>${active.catalog.nextCursor?`<button class="catalog-more" data-a="more" data-slot="${active.id}">Показать ещё</button>`:''}</aside>`:''}<div class="mkt-side"><button data-a="clean">${state.clean?'Показать UI':'Clean View'}</button><button data-a="demo">Демо композиции</button></div></section></main>`;if(state.camera&&state.stream){const v=$('#camera');v.srcObject=state.stream}}
async function camera(){if(state.camera){state.stream?.getTracks().forEach(t=>t.stop());state.stream=null;state.camera=false;draw();return}try{state.stream=await navigator.mediaDevices.getUserMedia({video:{facingMode:'environment'},audio:false});state.camera=true;draw()}catch{state.camera=true;draw()}}
function captureFrame(atMs){const v=$('#camera');if(!v||!v.videoWidth)return null;const c=document.createElement('canvas');const maxW=720,scale=Math.min(1,maxW/v.videoWidth);c.width=Math.round(v.videoWidth*scale);c.height=Math.round(v.videoHeight*scale);c.getContext('2d').drawImage(v,0,0,c.width,c.height);return{atMs,dataUrl:c.toDataURL('image/jpeg',.72)}}
async function captureBurst(){const frames=[];const start=performance.now();for(let i=0;i<4;i++){const f=captureFrame(Math.round(performance.now()-start));if(f)frames.push(f);if(i<3)await new Promise(r=>setTimeout(r,520))}return frames}
function fallbackComposition(q){state.backend='fallback';state.query=q;state.clarification=null;state.slots=['shelf','vase','book'].map((id,i)=>({id,label:{shelf:'Полка',vase:'Ваза',book:'Книга'}[id],anchor:{x:40+i*10,y:45-i*4},selected:fallbackInventory[id][0],searchQuery:id,category:id,attributes:{},catalog:{items:fallbackInventory[id],total:fallbackInventory[id].length,nextCursor:null}}));state.activeSlot='shelf';draw()}
function applyVision(result,q){state.query=q;state.clarification=null;state.backend='api';if(result.mode==='clarify'){state.slots=[];state.activeSlot=null;state.clarification=result.intent?.clarificationQuestion||'Уточни, пожалуйста, что именно нужно';draw();return}state.slots=(result.sceneSlots||[]).map((s,i)=>({id:s.slotId,label:s.label,anchor:{x:35+i*18,y:48-i*5},selected:s.currentOffer,searchQuery:s.searchQuery,category:s.category,attributes:s.attributes||{},catalog:s.catalog}));state.activeSlot=state.slots[0]?.id||null;draw()}
async function resolveQuery(q){state.processing=true;state.query=q;state.clarification=null;draw();try{const frames=await captureBurst();const res=await fetch('/api/vision/resolve',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({frames,voiceText:q,locale:'ru-RU',catalogLimit:24})});const json=await res.json();if(!res.ok)throw new Error(json.error||'Vision error');applyVision(json,q)}catch(error){if(q.toLowerCase().includes('полк')&&(q.toLowerCase().includes('ваз')||q.toLowerCase().includes('книг')))fallbackComposition(q);else{state.clarification='AI backend недоступен в этом окружении';state.backend='fallback';state.slots=[];draw()}}finally{state.processing=false;draw()}}
function voice(){const SR=window.SpeechRecognition||window.webkitSpeechRecognition;if(!SR){resolveQuery('Нужна полка, на которой стоит ваза и книга');return}const r=new SR();r.lang='ru-RU';r.interimResults=false;r.onstart=()=>{state.listening=true;draw()};r.onresult=e=>{state.listening=false;resolveQuery(e.results[0][0].transcript)};r.onerror=()=>{state.listening=false;draw()};r.onend=()=>{state.listening=false;draw()};r.start()}
async function loadMore(s){if(!s?.catalog?.nextCursor)return;try{const res=await fetch('/api/search/slots',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({slots:[{slotId:s.id,label:s.label,searchQuery:s.searchQuery,category:s.category,attributes:s.attributes,limit:24,cursor:s.catalog.nextCursor}]})});const json=await res.json();if(!res.ok)throw new Error(json.error||'Search error');const next=json.slots?.[0]?.catalog;if(next){s.catalog.items.push(...next.items);s.catalog.nextCursor=next.nextCursor;s.catalog.total=next.total;draw()}}catch{}}
root.addEventListener('click',e=>{const b=e.target.closest('[data-a]');if(!b)return;const a=b.dataset.a;if(a==='camera')camera();if(a==='voice')voice();if(a==='clean'){state.clean=!state.clean;draw()}if(a==='slot'){state.activeSlot=b.dataset.slot;state.catalogOpen=true;draw()}if(a==='catalog'){state.catalogOpen=!state.catalogOpen;draw()}if(a==='replace'){const s=slot(b.dataset.slot);const p=s?.catalog?.items.find(x=>x.id===b.dataset.id);if(s&&p){s.selected=p;state.catalogOpen=false;draw()}}if(a==='more')loadMore(slot(b.dataset.slot));if(a==='demo'){state.camera=true;fallbackComposition('Нужна полка, на которой стоит ваза и книга')}});
draw();
