const root=document.querySelector('#app');
const $=(s,r=document)=>r.querySelector(s);
const esc=v=>String(v??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;');
const catalog=[
 {id:'M-101',name:'Фара правая Focus III',price:25900,category:'auto',fit:'98%',scene:'garage'},
 {id:'M-102',name:'Фара левая Focus III',price:24100,category:'auto',fit:'94%',scene:'garage'},
 {id:'M-103',name:'Капот Ford Focus III',price:28500,category:'auto',fit:'91%',scene:'garage'},
 {id:'M-201',name:'Кресло Oslo',price:34900,category:'home',fit:'96%',scene:'living'},
 {id:'M-202',name:'Торшер Line',price:12900,category:'home',fit:'89%',scene:'living'},
 {id:'M-301',name:'Монитор 32” 4K',price:54900,category:'tech',fit:'95%',scene:'desk'}
];
let state={camera:false,clean:false,query:'',category:'auto',selected:null,stream:null,listening:false};
function money(v){return new Intl.NumberFormat('ru-RU').format(v)+' ₽'}
function draw(){root.innerHTML=`<main class="mkt"><header class="mkt-head"><div class="mkt-brand">EINEIRO <span>market</span></div><div class="mkt-status">${state.camera?'LIVE CAMERA':'READY'}</div></header><section class="mkt-stage ${state.clean?'clean':''}"><div class="mkt-scene"><video id="camera" autoplay playsinline muted></video><div class="scene-fallback scene-${state.category}"></div><div class="scan-lines"></div><div class="safe-zone"></div>${state.selected?`<div class="placed-product"><div class="placed-model">${esc(state.selected.name)}</div><span>${state.selected.fit} match</span></div>`:''}<div class="intent"><b>${state.query?esc(state.query):'Покажи, что хочешь'}</b><span>${state.query?'EINEIRO понял контекст и подбирает товары':'Камера и голос — основной интерфейс запроса'}</span></div></div><div class="mkt-controls"><button data-a="fav">♡</button><button class="camera-main ${state.camera?'on':''}" data-a="camera">◎</button><button data-a="voice">${state.listening?'●':'◉'}</button></div>${state.camera?`<div class="product-dock">${suggestions().map((p,i)=>`<button class="product-card ${state.selected?.id===p.id?'selected':''}" data-a="place" data-id="${p.id}"><span class="product-rank">0${i+1}</span><b>${esc(p.name)}</b><small>${p.fit} · ${money(p.price)}</small></button>`).join('')}</div>`:''}<div class="mkt-side"><button data-a="clean">${state.clean?'Показать UI':'Clean View'}</button><button data-a="cycle">Сменить сцену</button></div></section></main>`;if(state.camera&&state.stream){const v=$('#camera');v.srcObject=state.stream}}
function suggestions(){const xs=catalog.filter(x=>x.category===state.category);return xs.slice(0,3)}
async function camera(){if(state.camera){state.stream?.getTracks().forEach(t=>t.stop());state.stream=null;state.camera=false;draw();return}try{state.stream=await navigator.mediaDevices.getUserMedia({video:{facingMode:'environment'},audio:false});state.camera=true;draw()}catch{state.camera=true;draw()}}
function voice(){const SR=window.SpeechRecognition||window.webkitSpeechRecognition;if(!SR){state.query='Голосовой ввод недоступен — контекст определён по сцене';state.camera=true;draw();return}const r=new SR();r.lang='ru-RU';r.interimResults=false;r.onstart=()=>{state.listening=true;draw()};r.onresult=e=>{state.query=e.results[0][0].transcript;const q=state.query.toLowerCase();state.category=q.includes('крес')||q.includes('диван')||q.includes('дом')?'home':q.includes('монитор')||q.includes('комп')||q.includes('тех')?'tech':'auto';state.camera=true;state.listening=false;draw()};r.onerror=()=>{state.listening=false;draw()};r.onend=()=>{state.listening=false;draw()};r.start()}
root.addEventListener('click',e=>{const b=e.target.closest('[data-a]');if(!b)return;const a=b.dataset.a;if(a==='camera')camera();if(a==='voice')voice();if(a==='clean'){state.clean=!state.clean;draw()}if(a==='cycle'){state.category=state.category==='auto'?'home':state.category==='home'?'tech':'auto';state.selected=null;draw()}if(a==='place'){state.selected=catalog.find(x=>x.id===b.dataset.id)||null;draw()}});
draw();
