import {mkdir,readFile,readdir,unlink,writeFile} from 'node:fs/promises';
import path from 'node:path';
import crypto from 'node:crypto';

export class CompanyBackupService{
  constructor({store,backupDir=path.join(process.cwd(),'backups','companies'),retainPerCompany=12,now=()=>new Date()}={}){if(!store)throw new Error('store required');this.store=store;this.backupDir=backupDir;this.retainPerCompany=retainPerCompany;this.now=now;}
  async create(companyId){if(!companyId)throw new Error('companyId required');await mkdir(this.backupDir,{recursive:true});const payload=await this.store.exportCompany(companyId);const json=JSON.stringify(payload,null,2);const checksum=crypto.createHash('sha256').update(json).digest('hex');const stamp=this.now().toISOString().replace(/[:.]/g,'-');const file=path.join(this.backupDir,`${stamp}-company-${safe(companyId)}.json`);await writeFile(file,json,{mode:0o600});await writeFile(`${file}.sha256`,checksum,{mode:0o600});await this.prune(companyId);return {file,companyId,checksum,createdAt:this.now().toISOString(),size:Buffer.byteLength(json)};}
  async verify(file){const raw=await readFile(file,'utf8');const expected=(await readFile(`${file}.sha256`,'utf8')).trim();const actual=crypto.createHash('sha256').update(raw).digest('hex');const parsed=JSON.parse(raw);return {ok:actual===expected&&Boolean(parsed.companyId),file,companyId:parsed.companyId,checksum:actual};}
  async list(companyId=null){await mkdir(this.backupDir,{recursive:true});const names=(await readdir(this.backupDir)).filter(x=>x.endsWith('.json')).sort().reverse();return names.filter(x=>!companyId||x.includes(`company-${safe(companyId)}`)).map(name=>({name,file:path.join(this.backupDir,name)}));}
  async restore(file,{targetCompanyId=null}={}){const check=await this.verify(file);if(!check.ok)throw new Error('backup integrity check failed');const data=JSON.parse(await readFile(file,'utf8'));const companyId=targetCompanyId||data.companyId;for(const user of data.users||[])await this.store.putUser({...user,companyId});const repo=this.store.tenant({companyId});for(const rec of data.records||[]){const entity=rec.__entity||inferEntity(rec);const clean={...rec};delete clean.__entity;delete clean.__recordId;clean.companyId=companyId;if(entity&&clean.id)await repo.put(entity,clean)}for(const e of data.audit||[])await this.store.appendAudit({...e,companyId});for(const e of data.events||[])await this.store.appendEvent({...e,companyId});return {restored:true,sourceCompanyId:data.companyId,targetCompanyId:companyId,restoredAt:this.now().toISOString()};}
  async prune(companyId){const list=await this.list(companyId);for(const x of list.slice(this.retainPerCompany)){await unlink(x.file).catch(()=>{});await unlink(`${x.file}.sha256`).catch(()=>{});}return list.slice(0,this.retainPerCompany);}
}
function safe(v){return String(v).replace(/[^a-zA-Z0-9_-]/g,'_')}
function inferEntity(rec){if(rec.productId&&rec.quantity!=null)return'InventoryUnit';if(rec.email&&rec.role)return'User';return rec.entity||null}
