import assert from 'node:assert/strict';
import crypto from 'node:crypto';
import {mkdir,mkdtemp,readFile,rm,writeFile} from 'node:fs/promises';
import os from 'node:os';import path from 'node:path';
import {JsonFileStore} from './storage.mjs';
import {CompanyBackupService} from './company-backup.mjs';

const dir=await mkdtemp(path.join(os.tmpdir(),'eineiro-company-backup-'));
const store=await new JsonFileStore(path.join(dir,'db.json')).init();
const ctx={companyId:'c1',userId:'owner',role:'owner'};
await store.putUser({id:'u1',companyId:'c1',email:'a@b.c',role:'owner',active:true});
await store.tenant(ctx).put('Product',{id:'p1',name:'Товар'});
const evidenceId='modev_backup_1';
await store.tenant(ctx).put('ModerationEvidence',{id:evidenceId,moderationCaseId:'modcase_1',status:'active'});
const evidenceDir=path.join(dir,'evidence');
const tenantDir=crypto.createHash('sha256').update(ctx.companyId).digest('hex').slice(0,32);
const evidenceFile=path.join(evidenceDir,tenantDir,evidenceId+'.enc');
const encryptedEnvelope=Buffer.from('EINMOD1-test-encrypted-envelope');
await mkdir(path.dirname(evidenceFile),{recursive:true});
await writeFile(evidenceFile,encryptedEnvelope);
const svc=new CompanyBackupService({store,backupDir:path.join(dir,'backups'),evidenceDir,now:()=>new Date('2026-09-13T10:00:00Z')});
const b=await svc.create('c1');
assert.equal(b.evidenceFiles,1);
const check=await svc.verify(b.file);assert.equal(check.ok,true);assert.equal(check.companyId,'c1');
await store.tenant(ctx).remove('Product','p1');assert.equal(store.tenant(ctx).get('Product','p1'),null);
await rm(evidenceFile);
const restored=await svc.restore(b.file);
assert.equal(restored.evidenceFiles,1);
assert.equal(store.tenant(ctx).get('Product','p1').name,'Товар');
assert.deepEqual(await readFile(evidenceFile),encryptedEnvelope);
await assert.rejects(()=>svc.restore(b.file,{targetCompanyId:'c2'}),error=>error.code==='EVIDENCE_CROSS_TENANT_RESTORE_FORBIDDEN');
await rm(dir,{recursive:true,force:true});console.log('EINEIRO company backup tests: OK');
