import crypto from 'node:crypto';

export class DecisionEngine{
  constructor({repoFactory,policyEngine,now=()=>new Date()}={}){if(typeof repoFactory!=='function')throw new Error('repoFactory required');if(!policyEngine)throw new Error('policyEngine required');this.repoFactory=repoFactory;this.policyEngine=policyEngine;this.now=now;}
  async decide(ctx,{capability,action,resource,proposal,amount=null,confidence=null,customerImpact=null,affectedCount=null,externalDependency=false,reason='',expiresInMinutes=60}={}){
    const repo=this.repoFactory(ctx);const policy=await this.policyEngine.evaluate(ctx,{subjectType:'ai',subjectId:capability,role:ctx.role,action,resource,amount,confidence,customerImpact,affectedCount,externalDependency,meta:{scope:capability}});const status=policy.effect==='ALLOW'||policy.effect==='ALLOW_WITH_LIMIT'?'approved':policy.effect==='DENY'?'denied':'requires_approval';const rec={id:`decision_${crypto.randomUUID()}`,capability,action,resource,proposal:structuredClone(proposal),amount,confidence,customerImpact,affectedCount,externalDependency,reason,policy,status,expiresAt:new Date(this.now().getTime()+Math.max(1,Number(expiresInMinutes)||60)*60000).toISOString(),createdAt:this.now().toISOString(),executedAt:null,rolledBackAt:null};await repo.put('Decision',rec);if(status==='requires_approval')await repo.put('Exception',{id:`exc:${rec.id}`,type:'decision',title:`Требуется решение: ${action}`,detail:reason||resource,severity:policy.risk==='CRITICAL'||policy.risk==='HIGH'?'bad':'warn',requiresOwner:true,status:'open',decisionId:rec.id,createdAt:this.now().toISOString()});return rec;}
  async execute(ctx,decisionId,executor){const repo=this.repoFactory(ctx);const d=await repo.get('Decision',decisionId);if(!d)throw new Error('decision not found');if(d.status!=='approved')throw Object.assign(new Error('decision is not approved'),{code:'DECISION_NOT_APPROVED'});if(Date.parse(d.expiresAt)<=this.now().getTime())throw Object.assign(new Error('decision expired'),{code:'DECISION_EXPIRED'});const recheck=await this.policyEngine.evaluate(ctx,{subjectType:'ai',subjectId:d.capability,role:ctx.role,action:d.action,resource:d.resource,amount:d.amount,confidence:d.confidence,customerImpact:d.customerImpact,affectedCount:d.affectedCount,externalDependency:d.externalDependency,meta:{scope:d.capability}});if(!['ALLOW','ALLOW_WITH_LIMIT'].includes(recheck.effect))throw Object.assign(new Error('policy changed before execution'),{code:'DECISION_RECHECK_BLOCKED'});const result=await executor(d.proposal,d);const next={...d,status:'executed',executionResult:structuredClone(result),executedAt:this.now().toISOString(),policyAtExecution:recheck};await repo.put('Decision',next);return next;}
  async rollback(ctx,decisionId,rollbackFn){const repo=this.repoFactory(ctx);const d=await repo.get('Decision',decisionId);if(!d||d.status!=='executed')throw new Error('executed decision required');const policy=await this.policyEngine.evaluate(ctx,{subjectType:'ai',subjectId:d.capability,role:ctx.role,action:`rollback:${d.action}`,resource:d.resource,amount:d.amount,confidence:1,meta:{scope:d.capability}});if(policy.effect==='DENY')throw Object.assign(new Error('rollback denied by policy'),{code:'ROLLBACK_DENIED'});const result=await rollbackFn(d.executionResult,d);const next={...d,status:'rolled_back',rollbackResult:structuredClone(result),rolledBackAt:this.now().toISOString()};await repo.put('Decision',next);return next;}
}
