import crypto from 'node:crypto';

export class DemandLoopService{
  constructor({repoFactory,now=()=>new Date()}={}){if(typeof repoFactory!=='function')throw new Error('repoFactory required');this.repoFactory=repoFactory;this.now=now;}
  async perceptualFeedback(ctx,{identityId=null,sessionId=null,productId=null,offerId=null,signal,rawText=null,context={}}={}){
    if(!signal)throw new Error('signal required');const repo=this.repoFactory(ctx);const rec={id:`pf_${crypto.randomUUID()}`,identityId,sessionId,productId,offerId,signal,rawText,context:structuredClone(context),createdAt:this.now().toISOString()};await repo.put('PerceptualFeedback',rec);const delta={id:`pd_${crypto.randomUUID()}`,identityId,sessionId,signal,scope:'session',confidence:Number(context.confidence||0.7),sourceFeedbackId:rec.id,createdAt:this.now().toISOString()};await repo.put('PreferenceDelta',delta);return{feedback:rec,preferenceDelta:delta};
  }
  async createDemandIntent(ctx,{identityId=null,sessionId=null,intent,save=false,notifyWhenAvailable=false,budget=null,region=null,preorderWillingness=false}={}){
    if(!intent)throw new Error('intent required');const repo=this.repoFactory(ctx);const rec={id:`di_${crypto.randomUUID()}`,identityId,sessionId,intent:structuredClone(intent),saved:Boolean(save),notifyWhenAvailable:Boolean(notifyWhenAvailable),budget:budget==null?null:Number(budget),region,preorderWillingness:Boolean(preorderWillingness),status:'open',createdAt:this.now().toISOString()};await repo.put('DemandIntent',rec);return rec;
  }
  async createProductionOpportunity(ctx,{clusterId,category,specification={},evidence={}}={}){
    const repo=this.repoFactory(ctx);const cluster=await repo.get('DemandCluster',clusterId);if(!cluster)throw new Error('demand cluster not found');const quality=opportunityQuality(cluster,evidence);const rec={id:`po_${crypto.randomUUID()}`,clusterId,category,specification:structuredClone(specification),evidence:structuredClone(evidence),qualityScore:quality.score,confidence:quality.confidence,status:quality.score>=70?'open':'hold',createdAt:this.now().toISOString()};await repo.put('ProductionOpportunity',rec);return rec;
  }
  async feedbackAfterProduct(ctx,{productionOpportunityId,notified=0,opens=0,saves=0,preorders=0,purchases=0,returns=0,rejectionReasons=[],attributeMismatch=0}={}){
    const repo=this.repoFactory(ctx);const opp=await repo.get('ProductionOpportunity',productionOpportunityId);if(!opp)throw new Error('production opportunity not found');const conversion=notified?Number(purchases)/Number(notified):0;const falseDemand=notified>=20&&conversion<0.02;const rec={id:`pof_${crypto.randomUUID()}`,productionOpportunityId,notified:Number(notified),opens:Number(opens),saves:Number(saves),preorders:Number(preorders),purchases:Number(purchases),returns:Number(returns),rejectionReasons:structuredClone(rejectionReasons),attributeMismatch:Number(attributeMismatch),conversion,falseDemand,createdAt:this.now().toISOString()};await repo.put('ProductionOpportunityFeedback',rec);await repo.put('ProductionOpportunity',{...opp,status:falseDemand?'invalidated':opp.status,lastFeedbackId:rec.id,updatedAt:this.now().toISOString()});return rec;
  }
  async metrics(ctx){const repo=this.repoFactory(ctx);const [unserved,intents,opps,feedback]=await Promise.all([repo.list('UnservedDemand'),repo.list('DemandIntent'),repo.list('ProductionOpportunity'),repo.list('ProductionOpportunityFeedback')]);const converted=feedback.filter(x=>x.purchases>0).length;return{unservedDemandRate:rate(unserved.filter(x=>x.status==='open').length,Math.max(1,unserved.length+intents.length)),savedIntentCount:intents.filter(x=>x.saved).length,productionOpportunityCount:opps.length,demandToPurchaseConversion:rate(converted,Math.max(1,feedback.length)),falseDemandRate:rate(feedback.filter(x=>x.falseDemand).length,Math.max(1,feedback.length))};}
}
function opportunityQuality(cluster,evidence){const count=Number(cluster.count||0),strength=Number(cluster.averageStrength||cluster.strength||0),preorders=Number(evidence.preorders||0),saved=Number(evidence.savedIntents||0);const score=Math.min(100,count*4+strength*.45+preorders*8+saved*3);const confidence=Math.min(.99,.4+Math.min(.5,count/50)+Math.min(.09,preorders/100));return{score:Math.round(score),confidence:Number(confidence.toFixed(2))}}
function rate(a,b){return Number((Number(a||0)/Math.max(1,Number(b||1))).toFixed(4))}
