import crypto from 'node:crypto';

export class FulfillmentService{
  constructor({repoFactory,now=()=>new Date()}={}){if(typeof repoFactory!=='function')throw new Error('repoFactory required');this.repoFactory=repoFactory;this.now=now;}
  async registerOperator(ctx,input={}){const repo=this.repoFactory(ctx);const rec={id:input.id||`op_${crypto.randomUUID()}`,name:input.name||'Оператор',types:[...new Set(input.types||[])],rating:Number(input.rating||0),status:input.status||'active',companyId:input.companyId||null,createdAt:this.now().toISOString()};await repo.put('Operator',rec);return rec;}
  async addLocation(ctx,input={}){const repo=this.repoFactory(ctx);const rec={id:input.id||`loc_${crypto.randomUUID()}`,operatorId:input.operatorId,name:input.name||'Локация',region:input.region||null,geo:structuredClone(input.geo||null),capabilities:[...new Set(input.capabilities||[])],capacity:Number(input.capacity||0),load:Number(input.load||0),status:input.status||'active',createdAt:this.now().toISOString()};await repo.put('Location',rec);return rec;}
  async addServiceOffer(ctx,input={}){const repo=this.repoFactory(ctx);const rec={id:input.id||`svc_${crypto.randomUUID()}`,operatorId:input.operatorId,locationId:input.locationId,type:input.type,categoryIds:[...new Set(input.categoryIds||[])],price:Number(input.price||0),slaHours:Number(input.slaHours||0),capacity:Number(input.capacity||0),coverageAreas:[...new Set(input.coverageAreas||[])],capabilities:[...new Set(input.capabilities||[])],status:input.status||'active',createdAt:this.now().toISOString()};await repo.put('ServiceOffer',rec);return rec;}
  async assign(ctx,{orderId,type,region,categoryId,requiredCapabilities=[],maxPrice=null}={}){const repo=this.repoFactory(ctx);const [offers,operators,locations]=await Promise.all([repo.list('ServiceOffer'),repo.list('Operator'),repo.list('Location')]);const op=new Map(operators.map(x=>[x.id,x])),loc=new Map(locations.map(x=>[x.id,x]));const candidates=offers.filter(x=>x.status==='active'&&x.type===type).filter(x=>!x.categoryIds.length||x.categoryIds.includes(categoryId)).filter(x=>!x.coverageAreas.length||x.coverageAreas.includes(region)||x.coverageAreas.includes('*')).filter(x=>maxPrice==null||x.price<=maxPrice).filter(x=>requiredCapabilities.every(c=>x.capabilities.includes(c)||loc.get(x.locationId)?.capabilities?.includes(c))).map(x=>({offer:x,operator:op.get(x.operatorId),location:loc.get(x.locationId)})).filter(x=>x.operator?.status==='active'&&x.location?.status==='active').sort((a,b)=>score(b)-score(a));if(!candidates.length)throw Object.assign(new Error('fulfillment option not found'),{code:'FULFILLMENT_UNAVAILABLE'});const c=candidates[0];const rec={id:`ful_${crypto.randomUUID()}`,orderId,type,serviceOfferId:c.offer.id,operatorId:c.operator.id,locationId:c.location.id,price:c.offer.price,slaHours:c.offer.slaHours,status:'assigned',reason:{rating:c.operator.rating,load:c.location.load,capacity:c.location.capacity},createdAt:this.now().toISOString()};await repo.put('FulfillmentAssignment',rec);return rec;}
}
function score(x){const free=Math.max(0,Number(x.location.capacity||0)-Number(x.location.load||0));return Number(x.operator.rating||0)*2+Math.min(100,free)-Number(x.offer.price||0)/100-Number(x.offer.slaHours||0)}
