import crypto from 'node:crypto';

export class IdentityService{
  constructor({repoFactory,now=()=>new Date()}={}){if(typeof repoFactory!=='function')throw new Error('repoFactory required');this.repoFactory=repoFactory;this.now=now;}
  async createAnonymous(ctx,{sessionId=null,state={}}={}){const repo=this.repoFactory(ctx);const rec={id:`anon_${crypto.randomUUID()}`,sessionId:sessionId||crypto.randomUUID(),kind:'anonymous',state:structuredClone(state),createdAt:this.now().toISOString(),updatedAt:this.now().toISOString()};await repo.put('AnonymousIdentity',rec);return rec;}
  async createIdentity(ctx,{displayName=null,locale='ru-RU'}={}){const repo=this.repoFactory(ctx);const rec={id:`identity_${crypto.randomUUID()}`,status:'active',displayName,locale,createdAt:this.now().toISOString(),updatedAt:this.now().toISOString()};await repo.put('Identity',rec);await repo.put('BuyerProfile',{id:`buyer:${rec.id}`,identityId:rec.id,preferences:{},privacy:{personalization:true,marketing:false},createdAt:this.now().toISOString()});return rec;}
  async addMembership(ctx,{identityId,companyId,role,capabilities=[]}={}){if(!identityId||!companyId||!role)throw new Error('identityId/companyId/role required');const repo=this.repoFactory(ctx);const rec={id:`membership:${identityId}:${companyId}:${role}`,identityId,companyId,role,capabilities:[...new Set(capabilities)],status:'active',createdAt:this.now().toISOString()};await repo.put('CompanyMembership',rec);return rec;}
  async migrateAnonymous(ctx,{anonymousId,identityId}={}){const repo=this.repoFactory(ctx);const anon=await repo.get('AnonymousIdentity',anonymousId);if(!anon)throw new Error('anonymous identity not found');if(anon.status==='migrated'){if(anon.identityId!==identityId)throw Object.assign(new Error('anonymous identity already migrated'),{code:'ANONYMOUS_IDENTITY_CONFLICT'});return await repo.get('SavedData',`saved:${identityId}`)||{id:`saved:${identityId}`,identityId,items:[]};}const saved=await repo.get('SavedData',`saved:${identityId}`)||{id:`saved:${identityId}`,identityId,items:[]};const carry=anon.state||{};const migratedAt=this.now().toISOString();for(const kind of ['cart','saved','intent','context','scene','offer','selectedOffers','draftOrder','visionContext','savedDemandDraft'])if(carry[kind]!=null&&!saved.items.some(x=>x.migrationSource===anonymousId&&x.kind===kind))saved.items.push({kind,value:structuredClone(carry[kind]),migrationSource:anonymousId,migratedAt});await repo.put('SavedData',saved);await repo.put('AnonymousIdentity',{...anon,status:'migrated',identityId,migratedAt});await repo.put('IdentityMigration',{id:`migration:${anonymousId}`,anonymousId,identityId,status:'completed',itemCount:saved.items.filter(x=>x.migrationSource===anonymousId).length,completedAt:migratedAt});return saved;}
  async linkProvider(ctx,{identityId,provider,subject,verified=true}={}){if(!identityId||!provider||!subject)throw new Error('identity/provider/subject required');const repo=this.repoFactory(ctx);const existing=(await repo.list('IdentityProviderLink')).find(x=>x.provider===provider&&x.subject===subject);if(existing&&existing.identityId!==identityId)throw Object.assign(new Error('provider identity conflict'),{code:'IDENTITY_LINK_CONFLICT'});const rec={id:`idp:${provider}:${subject}`,identityId,provider,subject,verified:Boolean(verified),createdAt:this.now().toISOString()};await repo.put('IdentityProviderLink',rec);return rec;}
  async deactivate(ctx,identityId,{reason='voluntary'}={}){const repo=this.repoFactory(ctx);const i=await repo.get('Identity',identityId);if(!i)throw new Error('identity not found');const next={...i,status:'deactivated',deactivationReason:reason,deactivatedAt:this.now().toISOString()};await repo.put('Identity',next);return next;}
}

export class SavedDataService{
  constructor({repoFactory,now=()=>new Date()}={}){this.repoFactory=repoFactory;this.now=now;}
  async add(ctx,identityId,{kind,value,source=null}={}){const repo=this.repoFactory(ctx);const id=`saved:${identityId}`;const rec=await repo.get('SavedData',id)||{id,identityId,items:[]};rec.items.push({id:crypto.randomUUID(),kind,value:structuredClone(value),source,createdAt:this.now().toISOString()});await repo.put('SavedData',rec);return rec;}
  async list(ctx,identityId){return (await this.repoFactory(ctx).get('SavedData',`saved:${identityId}`))?.items||[];}
}
