import assert from 'node:assert/strict';
import {MemoryRepository} from './core.mjs';
import {IdentityService,SavedDataService} from './identity-core.mjs';
import {PrivacyGateway} from './privacy-gateway.mjs';
import {SavedDemandService} from './saved-demand.mjs';
import {BuyerNotificationEngine} from './buyer-notifications.mjs';

const ctx={companyId:'platform',userId:'system',role:'admin'};const repo=new MemoryRepository();const wrap={put:(e,r)=>repo.put(ctx,e,r),get:(e,id)=>repo.get(ctx,e,id),list:e=>repo.list(ctx,e)};
const identity=new IdentityService({repoFactory:()=>wrap,now:()=>new Date('2026-09-13T12:00:00Z')});const anon=await identity.createAnonymous(ctx,{state:{cart:['o1'],saved:['p1'],intent:{category:'home.chair'},offer:'off1',draftOrder:{id:'d1'},visionContext:{slot:'chair'}}});const id=await identity.createIdentity(ctx,{displayName:'Покупатель'});const migrated=await identity.migrateAnonymous(ctx,{anonymousId:anon.id,identityId:id.id});assert.equal(migrated.items.length,6);await identity.addMembership(ctx,{identityId:id.id,companyId:'c1',role:'owner'});await identity.addMembership(ctx,{identityId:id.id,companyId:'c2',role:'employee'});assert.equal(repo.list(ctx,'CompanyMembership').length,2);
const saved=new SavedDataService({repoFactory:()=>wrap});await saved.add(ctx,id.id,{kind:'favorite',value:'p2'});assert.ok((await saved.list(ctx,id.id)).some(x=>x.kind==='favorite'));
const privacy=new PrivacyGateway();const clean=privacy.prepareExternal({text:'Пиши мне test@example.com или +7 999 123-45-67',context:{fullAddress:'secret',note:'номер А123ВС77'},media:[{id:'raw',type:'image',sanitized:false},{id:'safe',type:'image',sanitized:true,url:'safe://1'}]});assert.equal(clean.text.includes('test@example.com'),false);assert.equal(clean.text.includes('999 123'),false);assert.equal(clean.media.length,1);assert.equal('fullAddress' in clean.context,false);
repo.put(ctx,'Product',{id:'p3',categoryId:'home.chair',attributes:{color:'green'}});repo.put(ctx,'Offer',{id:'off3',productId:'p3',sellerId:'s1',price:25000,stock:2,region:'Москва',condition:'new',deliveryOptions:[{nationwide:true}]});const demand=new SavedDemandService({repoFactory:()=>wrap});await demand.save(ctx,{identityId:id.id,intent:{category:'home.chair',attributes:{color:'green'}},priceRange:[20000,30000],region:'Москва',condition:'new'});const matches=await demand.matchOffer(ctx,repo.get(ctx,'Offer','off3'),{product:repo.get(ctx,'Product','p3'),confidence:.95});assert.equal(matches[0].exact,true);
const notify=new BuyerNotificationEngine({repoFactory:()=>wrap,now:()=>new Date('2026-09-13T12:00:00Z')});const normal=await notify.enqueue(ctx,{identityId:id.id,type:'recommendation',recommendation:true,confidence:.7,title:'Обычная рекомендация'});assert.equal(normal.notification.push,false);const paid=await notify.enqueue(ctx,{identityId:id.id,type:'promotion',paidPromotion:true,recommendation:true,confidence:.99,title:'Реклама'});assert.equal(paid.notification.push,false);const found=await notify.enqueue(ctx,{identityId:id.id,type:'saved-demand',exactSavedDemand:true,confidence:.95,objectId:'off3',title:'Появился вариант'});assert.equal(found.notification.priority,'MATCH_FOUND');assert.equal(found.notification.push,true);const dup=await notify.enqueue(ctx,{identityId:id.id,type:'saved-demand',exactSavedDemand:true,confidence:.95,objectId:'off3',title:'Появился вариант'});assert.equal(dup.duplicate,true);
console.log('EINEIRO identity/privacy/notifications tests: OK');
