function splitCsvLine(line,delimiter=','){const out=[];let cur='';let q=false;for(let i=0;i<line.length;i++){const c=line[i];if(c==='"'){if(q&&line[i+1]==='"'){cur+='"';i++;}else q=!q;}else if(c===delimiter&&!q){out.push(cur);cur='';}else cur+=c}out.push(cur);return out}
export function parseCsv(text,{delimiter=','}={}){const lines=String(text||'').replace(/^\uFEFF/,'').split(/\r?\n/).filter(Boolean);if(!lines.length)return[];const head=splitCsvLine(lines[0],delimiter).map(x=>x.trim());return lines.slice(1).map(line=>Object.fromEntries(splitCsvLine(line,delimiter).map((v,i)=>[head[i],v]))) }
export function parseSimpleXml(text){const src=String(text||'');const rows=[];for(const match of src.matchAll(/<item\b[^>]*>([\s\S]*?)<\/item>/gi)){const row={};for(const f of match[1].matchAll(/<([\w.-]+)>([\s\S]*?)<\/\1>/g))row[f[1]]=f[2].replace(/<!\[CDATA\[|\]\]>/g,'').trim();rows.push(row)}return rows}
export function mapRecord(row,mapping={}){const get=(name,...alts)=>{const key=mapping[name]||[name,...alts].find(k=>row[k]!=null);return key?row[key]:undefined};return {id:String(get('id','article','sku')||'').trim(),name:String(get('name','title')||'').trim(),category:String(get('category','categoryId')||'').trim(),price:Number(String(get('price','cost')||0).replace(',','.'))||0,quantity:Number(get('quantity','qty','stock')||0)||0,storageAddress:String(get('storageAddress','shelf','location')||'').trim(),attributes:Object.fromEntries(Object.entries(row).filter(([k])=>!new Set(Object.values(mapping)).has(k)&&!['id','article','sku','name','title','category','categoryId','price','cost','quantity','qty','stock','storageAddress','shelf','location'].includes(k)))} }
export class ImportService{
 constructor({repoFactory,audit=null,events=null}={}){this.repoFactory=repoFactory;this.audit=audit;this.events=events}
 parse(format,text,options={}){if(format==='csv')return parseCsv(text,options);if(format==='xml')return parseSimpleXml(text);throw Object.assign(new Error('unsupported format'),{status:400,code:'UNSUPPORTED_FORMAT'})}
 async importProducts(ctx,{format,text,mapping={},reverseInventory=false,options={}}={}){const rows=this.parse(format,text,options);const repo=this.repoFactory(ctx);const imported=[];const errors=[];for(let i=0;i<rows.length;i++){try{const p=mapRecord(rows[i],mapping);if(!p.id||!p.name)throw new Error('id/name required');const product=await repo.put('Product',{id:p.id,name:p.name,category:p.category||'other',price:p.price,attributes:p.attributes,imported:true});await repo.put('InventoryUnit',{id:`inv:${p.id}`,productId:p.id,quantity:p.quantity,storageAddress:reverseInventory?'':p.storageAddress,needsPlacement:Boolean(reverseInventory)});imported.push(product)}catch(e){errors.push({row:i+2,error:e.message})}}
  this.events?.emit?.(ctx,'import.completed',{format,total:rows.length,imported:imported.length,errors:errors.length,reverseInventory});this.audit?.write?.(ctx,{action:'import.products',entity:'ImportJob',entityId:`${Date.now()}`,meta:{format,total:rows.length,imported:imported.length,errors:errors.length,reverseInventory}});return{total:rows.length,imported:imported.length,errors};}
}
