import crypto from 'node:crypto';

export class NegotiationService{
  constructor({repoFactory,decisionEngine=null,now=()=>new Date()}={}){if(typeof repoFactory!=='function')throw new Error('repoFactory required');this.repoFactory=repoFactory;this.decisionEngine=decisionEngine;this.now=now;}
  async open(ctx,{offerId,buyerId,mode='offer_price',proposedPrice=null,message='',expiresInMinutes=60}={}){
    const repo=this.repoFactory(ctx);const offer=await repo.get('Offer',offerId);if(!offer)throw new Error('offer not found');
    const rec={id:`neg_${crypto.randomUUID()}`,offerId,productId:offer.productId,sellerId:offer.sellerId,buyerId,mode,askPrice:Number(offer.price||0),proposedPrice:proposedPrice==null?null:Number(proposedPrice),message,status:'open',round:1,history:[],expiresAt:new Date(this.now().getTime()+Math.max(5,Number(expiresInMinutes)||60)*60000).toISOString(),createdAt:this.now().toISOString(),updatedAt:this.now().toISOString()};await repo.put('Negotiation',rec);return rec;
  }
  async counter(ctx,id,{actor='seller',price,message=''}={}){const repo=this.repoFactory(ctx);const n=await repo.get('Negotiation',id);if(!n)throw new Error('negotiation not found');if(n.status!=='open')throw new Error('negotiation closed');if(Date.parse(n.expiresAt)<=this.now().getTime())throw Object.assign(new Error('negotiation expired'),{code:'NEGOTIATION_EXPIRED'});const history=[...(n.history||[]),{round:n.round,actor,price:Number(price),message,at:this.now().toISOString()}];const next={...n,proposedPrice:Number(price),message,status:'open',round:n.round+1,history,updatedAt:this.now().toISOString()};await repo.put('Negotiation',next);return next;}
  async aiCounter(ctx,id,{targetPrice,minPrice,maxDiscountPercent=7,confidence=.9}={}){const repo=this.repoFactory(ctx);const n=await repo.get('Negotiation',id);if(!n)throw new Error('negotiation not found');const ask=Number(n.askPrice||0);const floor=Math.max(Number(minPrice||0),ask*(1-Number(maxDiscountPercent||0)/100));const desired=Math.max(floor,Math.min(ask,Number(targetPrice||ask)));if(this.decisionEngine){const d=await this.decisionEngine.decide(ctx,{capability:'sales',action:'negotiate_price',resource:'Offer',proposal:{negotiationId:id,price:desired},amount:desired,confidence,customerImpact:'medium',reason:`AI counter-offer ${desired}`});if(d.status!=='approved')return{decision:d,negotiation:n};await this.decisionEngine.execute(ctx,d.id,async()=>({negotiationId:id,price:desired}));}
    const next=await this.counter(ctx,id,{actor:'ai',price:desired,message:'Предлагаю цену в допустимом диапазоне.'});return{negotiation:next,price:desired};}
  async accept(ctx,id,{actor='buyer'}={}){const repo=this.repoFactory(ctx);const n=await repo.get('Negotiation',id);if(!n)throw new Error('negotiation not found');const next={...n,status:'accepted',acceptedBy:actor,acceptedPrice:Number(n.proposedPrice??n.askPrice),updatedAt:this.now().toISOString()};await repo.put('Negotiation',next);return next;}
  async reject(ctx,id,{actor='seller',reason=''}={}){const repo=this.repoFactory(ctx);const n=await repo.get('Negotiation',id);if(!n)throw new Error('negotiation not found');const next={...n,status:'rejected',rejectedBy:actor,rejectReason:reason,updatedAt:this.now().toISOString()};await repo.put('Negotiation',next);return next;}
}
