export class ObservabilityService{
  constructor({repoFactory,now=()=>new Date()}={}){if(typeof repoFactory!=='function')throw new Error('repoFactory required');this.repoFactory=repoFactory;this.now=now;}
  async record(ctx,{kind,name,status='ok',latencyMs=null,cost=null,attempt=1,error=null,meta={}}={}){const repo=this.repoFactory(ctx);const rec={id:`obs:${kind}:${name}:${this.now().getTime()}:${Math.random().toString(36).slice(2,8)}`,kind,name,status,latencyMs:latencyMs==null?null:Number(latencyMs),cost:cost==null?null:Number(cost),attempt:Number(attempt||1),error:error?String(error):null,meta:structuredClone(meta),createdAt:this.now().toISOString()};await repo.put('ObservabilityRecord',rec);return rec;}
  async snapshot(ctx){
    const repo=this.repoFactory(ctx);const [obs,jobs,channels,connectorStates,decisions,policies,providerHealth,providerRuns,eventDeliveries,platformEvents]=await Promise.all([repo.list('ObservabilityRecord'),repo.list('Job'),repo.list('ChannelConnection'),repo.list('ConnectorHealth'),repo.list('Decision'),repo.list('PolicyDecision'),repo.list('AiProviderHealth'),repo.list('AiProviderRun'),repo.list('EventDelivery'),repo.list('PlatformEvent')]);
    const recent=obs.slice(-500);const aiObs=recent.filter(x=>x.kind==='ai_provider');const webhook=recent.filter(x=>x.kind==='webhook');const service=recent.filter(x=>x.kind==='service');
    const dlqJobs=jobs.filter(x=>['failed','dead_letter'].includes(x.status)),dlqEvents=eventDeliveries.filter(x=>x.status==='dead_letter');const retries=jobs.filter(x=>Number(x.attempts||x.attempt||0)>1).length+eventDeliveries.filter(x=>Number(x.attempts||0)>1||x.status==='retry').length;
    const failedDecisions=decisions.filter(x=>['failed','denied','expired'].includes(x.status));const policyDenials=policies.filter(x=>x.effect==='DENY');const legacyConnected=channels.filter(x=>x.status==='connected').length,legacyErrors=channels.filter(x=>x.status==='error').length;const frameworkHealthy=connectorStates.filter(x=>x.status==='healthy').length,frameworkErrors=connectorStates.filter(x=>['error','degraded'].includes(x.status)).length;
    const providerCalls=providerRuns.length+aiObs.length;const providerLatencies=[...providerRuns.map(x=>Number(x.latencyMs)),...aiObs.map(x=>Number(x.latencyMs))];const providerErrors=providerHealth.filter(x=>['down','degraded','error'].includes(x.status)).length+aiObs.filter(x=>x.status!=='ok').length;
    return{generatedAt:this.now().toISOString(),serviceHealth:aggregate(service),queueHealth:{queued:jobs.filter(x=>x.status==='queued').length,running:jobs.filter(x=>x.status==='running').length,retry:jobs.filter(x=>x.status==='retry').length,failed:jobs.filter(x=>x.status==='failed').length,dlq:dlqJobs.length+dlqEvents.length,retries,eventPending:platformEvents.filter(x=>['pending','partial'].includes(x.status)).length,eventDeadLetter:platformEvents.filter(x=>x.status==='dead_letter').length},connectorHealth:{total:Math.max(channels.length,connectorStates.length),connected:legacyConnected+frameworkHealthy,error:legacyErrors+frameworkErrors,legacy:channels.map(x=>({id:x.id||x.channel,status:x.status,enabled:x.enabled!==false})),framework:connectorStates.map(x=>({id:x.connectorId||x.id,status:x.status,lastSuccessAt:x.lastSuccessAt||null,lastFailureAt:x.lastFailureAt||null,lastError:x.lastError||null}))},webhookFailures:webhook.filter(x=>x.status!=='ok').length,aiProvider:{calls:providerCalls,avgLatencyMs:avg(providerLatencies),cost:sum(aiObs.map(x=>x.cost)),errors:providerErrors,providers:providerHealth.map(x=>({id:x.providerId||x.id,status:x.status,latencyMs:x.latencyMs,costScore:x.costScore,qualityScore:x.qualityScore}))},decisionFailures:failedDecisions.length,policyDenials:policyDenials.length,retries,dlqSize:dlqJobs.length+dlqEvents.length,recentFailures:recent.filter(x=>x.status!=='ok').slice(-50).reverse()};
  }
}
function aggregate(rows){if(!rows.length)return{status:'unknown',checks:0,failures:0,avgLatencyMs:0};const failures=rows.filter(x=>x.status!=='ok').length;return{status:failures===0?'ok':failures/rows.length<.1?'degraded':'critical',checks:rows.length,failures,avgLatencyMs:avg(rows.map(x=>x.latencyMs))}}
function avg(v){const a=v.filter(Number.isFinite);return a.length?Math.round(a.reduce((s,x)=>s+x,0)/a.length):0}function sum(v){return Number(v.filter(Number.isFinite).reduce((s,x)=>s+x,0).toFixed(4))}
