import assert from 'node:assert/strict';
import {MemoryRepository} from './core.mjs';
import {AcquisitionConnector,MarketingConnectorRegistry,createSilentRunConnectorRegistry} from './marketing-connector-sdk.mjs';
import {PlatformAcquisitionService,silentRunMarketingFlags} from './platform-acquisition.mjs';

const ctx={companyId:'platform',userId:'root-owner',identityId:'root-owner',role:'admin'};const memory=new MemoryRepository();const repo={put:(e,r)=>memory.put(ctx,e,r),get:(e,id)=>memory.get(ctx,e,id),list:e=>memory.list(ctx,e)};
const unconfigured=createSilentRunConnectorRegistry();assert.deepEqual(unconfigured.list().map(x=>x.state),['DISCOVERED','DISCOVERED']);assert.ok(unconfigured.list().every(x=>x.secretExposed===false));
let paused=false;const driver={authenticate:async()=>({ok:true}),certify:async()=>({realPublicationVerified:true,liveMetricsVerified:true,verifiedAt:'2026-09-14T10:00:00Z'}),publish:async()=>({externalCampaignId:'external-1'}),pause:async()=>{paused=true;}};const connector=new AcquisitionConnector({id:'yandex_direct',label:'Yandex Direct',credentialRef:'secret://yandex',driver,capabilities:['TEXT','SEARCH','BUDGET_CONTROL','PAUSE_RESUME','REALTIME_METRICS','UTM_TRACKING']});await connector.authenticate();await connector.certify();const registry=new MarketingConnectorRegistry().register(connector);
const svc=new PlatformAcquisitionService({repoFactory:()=>repo,connectorRegistry:registry,policyEngine:{evaluate:async()=>({effect:'ALLOW'})},financeGuard:{authorize:async()=>({decision:'ALLOW'})},flags:silentRunMarketingFlags({}),limits:{minSpend:100,minResolvedIntents:5},now:()=>new Date('2026-09-14T12:00:00Z')});
await assert.rejects(()=>svc.createCampaign(ctx,{channel:'yandex_direct',dailyBudget:100,sellerId:'seller-1'}),error=>error.code==='PLATFORM_BUDGET_SELLER_TARGET_FORBIDDEN');
const campaign=await svc.createCampaign(ctx,{channel:'yandex_direct',dailyBudget:100,goal:'RESOLVED_INTENT'});assert.equal(campaign.destination,'EINEIRO_PLATFORM');const live=await svc.launch(ctx,{campaignId:campaign.id});assert.equal(live.status,'LIVE');
await assert.rejects(()=>svc.recordAttribution(ctx,{type:'AD_CLICK',attributionId:'a1',sessionId:'s1',email:'leak@example.com'}),error=>error.code==='PII_IN_ATTRIBUTION_FORBIDDEN');await svc.recordAttribution(ctx,{type:'AD_CLICK',attributionId:'a1',sessionId:'s1',campaignId:campaign.id,channel:'yandex_direct'});
const collecting=await svc.recordExperiment(ctx,{campaignId:campaign.id,variantId:'A',metrics:{spend:50,resolvedIntents:2}});assert.equal(collecting.status,'COLLECTING');const eligible=await svc.recordExperiment(ctx,{campaignId:campaign.id,variantId:'A',metrics:{spend:50,resolvedIntents:3,sessions:100,errors:1,attributions:100,falseAttributions:1}});assert.equal(eligible.status,'ELIGIBLE');
const report=await svc.dailyReport(ctx);assert.equal(report.contour,'PLATFORM_ACQUISITION');assert.equal(report.resolvedIntents,5);
await svc.setKillSwitch(ctx,{enabled:true,reason:'incident'});assert.equal(paused,true);await assert.rejects(()=>svc.createCampaign(ctx,{channel:'yandex_direct',dailyBudget:10}),error=>error.code==='PLATFORM_ACQUISITION_KILLED');
const unsafe=new PlatformAcquisitionService({repoFactory:()=>repo,connectorRegistry:registry,flags:{platformAcquisitionEnabled:true,sellerCampaignsEnabled:true,sellerAdConnectorsEnabled:false,sponsoredShowcaseEnabled:false}});await svc.setKillSwitch(ctx,{enabled:false});await assert.rejects(()=>unsafe.createCampaign(ctx,{channel:'yandex_direct'}),error=>error.code==='SILENT_RUN_CONTOUR_VIOLATION');
console.log('EINEIRO platform acquisition tests: OK');
