import crypto from 'node:crypto';

export class ProcurementService{
  constructor({repoFactory,now=()=>new Date(),financeGate=null,warehouseGate=null,policyGate=null}={}){if(typeof repoFactory!=='function')throw new Error('repoFactory required');this.repoFactory=repoFactory;this.now=now;this.financeGate=financeGate;this.warehouseGate=warehouseGate;this.policyGate=policyGate;}
  async propose(ctx,{productId=null,demandClusterId=null,quantity=1,unitCost=0,supplierId=null,reason='demand'}={}){
    const repo=this.repoFactory(ctx);const proposal={id:`proc_${crypto.randomUUID()}`,productId,demandClusterId,quantity:Number(quantity)||1,unitCost:Number(unitCost)||0,totalCost:(Number(quantity)||1)*(Number(unitCost)||0),supplierId,reason,status:'proposed',financeDecision:'pending',warehouseDecision:'pending',policyDecision:'pending',createdAt:this.now().toISOString(),updatedAt:this.now().toISOString()};await repo.put('ProcurementProposal',proposal);return proposal;
  }
  async evaluate(ctx,proposalId){const repo=this.repoFactory(ctx);const p=await repo.get('ProcurementProposal',proposalId);if(!p)throw new Error('proposal not found');const finance=this.financeGate?await this.financeGate({ctx,proposal:p}):{decision:'REVIEW',reason:'finance gate unavailable'};const warehouse=this.warehouseGate?await this.warehouseGate({ctx,proposal:p}):{decision:'REVIEW',reason:'warehouse gate unavailable'};const policy=this.policyGate?await this.policyGate({ctx,proposal:p}):{decision:'ALLOW'};const next={...p,financeDecision:finance.decision,warehouseDecision:warehouse.decision,policyDecision:policy.decision,gateReasons:{finance:finance.reason||null,warehouse:warehouse.reason||null,policy:policy.reason||null},status:decisionStatus(finance.decision,warehouse.decision,policy.decision),evaluatedAt:this.now().toISOString(),updatedAt:this.now().toISOString()};await repo.put('ProcurementProposal',next);return next;}
  async confirm(ctx,proposalId){const repo=this.repoFactory(ctx);let p=await this.evaluate(ctx,proposalId);if(p.financeDecision!=='ALLOW'||p.warehouseDecision!=='ALLOW'||!['ALLOW','ALLOW_WITH_LIMIT'].includes(p.policyDecision))throw Object.assign(new Error('procurement blocked by gates'),{code:'PROCUREMENT_BLOCKED',proposal:p});p=await this.evaluate(ctx,proposalId);if(p.financeDecision!=='ALLOW'||p.warehouseDecision!=='ALLOW'||!['ALLOW','ALLOW_WITH_LIMIT'].includes(p.policyDecision))throw Object.assign(new Error('procurement changed before confirmation'),{code:'PROCUREMENT_RECHECK_BLOCKED',proposal:p});const order={id:`po_${crypto.randomUUID()}`,proposalId:p.id,productId:p.productId,demandClusterId:p.demandClusterId,quantity:p.quantity,unitCost:p.unitCost,totalCost:p.totalCost,supplierId:p.supplierId,status:'created',createdAt:this.now().toISOString()};await repo.put('PurchaseOrder',order);await repo.put('ProcurementProposal',{...p,status:'ordered',purchaseOrderId:order.id,updatedAt:this.now().toISOString()});return order;}
}
function decisionStatus(f,w,p){if([f,w,p].includes('DENY')||[f,w].includes('STOP'))return'blocked';if(f==='ALLOW'&&w==='ALLOW'&&['ALLOW','ALLOW_WITH_LIMIT'].includes(p))return'ready';return'review'}
