import assert from 'node:assert/strict';
import {MemoryRepository} from './core.mjs';
import {CategorySchemaService} from './category-schema.mjs';
import {CompatibilityGate} from './compatibility-gate.mjs';
import {OfferRankingService} from './offer-ranking.mjs';
import {SearchEngineV2} from './search-engine-v2.mjs';

const ctx={companyId:'c1',userId:'u1',role:'owner'};const repo=new MemoryRepository();const wrap={put:(e,r)=>repo.put(ctx,e,r),get:(e,id)=>repo.get(ctx,e,id),list:e=>repo.list(ctx,e)};
await repo.put(ctx,'Product',{id:'p1',name:'Фильтр A',categoryId:'filters',attributes:{thread:'M20',brand:'X'}});await repo.put(ctx,'Product',{id:'p2',name:'Фильтр B',categoryId:'filters',attributes:{thread:'M18',brand:'X'}});
await repo.put(ctx,'Offer',{id:'o1',productId:'p1',sellerId:'s1',status:'active',moderationStatus:'AUTO_APPROVED',moderationCaseId:'mod-o1',stock:3,price:1000,visualAssetReady:true,visualQualityScore:90,deliveryOptions:[{nationwide:true}],freshnessAt:'2026-09-13T00:00:00Z'});await repo.put(ctx,'Offer',{id:'o2',productId:'p2',sellerId:'s1',status:'active',moderationStatus:'AUTO_APPROVED',moderationCaseId:'mod-o2',stock:3,price:900,visualAssetReady:true,visualQualityScore:90,deliveryOptions:[{nationwide:true}],freshnessAt:'2026-09-13T00:00:00Z'});await repo.put(ctx,'SellerScore',{id:'seller-score:s1',sellerId:'s1',score:90});
const schema=new CategorySchemaService({repoFactory:()=>wrap});await schema.put(ctx,{categoryId:'filters',mandatoryFields:['thread'],compatibilityRules:[{key:'thread',productAttribute:'thread',operator:'eq',required:true}]});const gate=new CompatibilityGate({repoFactory:()=>wrap,schemaService:schema});const ranking=new OfferRankingService({repoFactory:()=>wrap,now:()=>new Date('2026-09-13T12:00:00Z')});const search=new SearchEngineV2({repoFactory:()=>wrap,categorySchema:schema,compatibilityGate:gate,offerRanking:ranking});const result=await search.search(ctx,{query:'Фильтр',intent:{category:'filters',attributes:{brand:'X'},compatibility:{thread:'M20'}},context:{thread:'M20'},limit:10});assert.equal(result.llmSelectedFinalList,false);assert.equal(result.items.length,1);assert.equal(result.items[0].offerId,'o1');console.log('EINEIRO Search Engine V2 tests: OK');
